services:
  autosender:
    image: ghcr.io/stufently/tgautoreplybot:latest  # Образ из GHCR
    container_name: autosender
    volumes:
      # Монтируем директории с данными
      - ./tdatas:/app/tdatas
      - ./sessions:/app/sessions
    env_file:
      - .env  # Монтируем .env файл с переменными окружения
    restart: unless-stopped
